// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwpNydEh8HfjWbvOkP2ntbguuXB3xjvcs',
    appId: '1:858838546933:web:6d4407fc3f16a61fb048bc',
    messagingSenderId: '858838546933',
    projectId: 'instagramclone-bbbee',
    authDomain: 'instagramclone-bbbee.firebaseapp.com',
    storageBucket: 'instagramclone-bbbee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5phHLNtQ0pUS7FvAHWuCmh5av44g6uA',
    appId: '1:858838546933:android:f0a1fcc16e19c68fb048bc',
    messagingSenderId: '858838546933',
    projectId: 'instagramclone-bbbee',
    storageBucket: 'instagramclone-bbbee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCkNZk0fo_Cp1Z-9QhVBqLFEDthXSQBAY',
    appId: '1:858838546933:ios:e2907590ed0f819ab048bc',
    messagingSenderId: '858838546933',
    projectId: 'instagramclone-bbbee',
    storageBucket: 'instagramclone-bbbee.appspot.com',
    iosBundleId: 'com.example.snapmirror',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCkNZk0fo_Cp1Z-9QhVBqLFEDthXSQBAY',
    appId: '1:858838546933:ios:e2907590ed0f819ab048bc',
    messagingSenderId: '858838546933',
    projectId: 'instagramclone-bbbee',
    storageBucket: 'instagramclone-bbbee.appspot.com',
    iosBundleId: 'com.example.snapmirror',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn70fasHeNSS4RijB41VlM8HEYiCcvyNA',
    appId: '1:858838546933:web:327c615a04babdd4b048bc',
    messagingSenderId: '858838546933',
    projectId: 'instagramclone-bbbee',
    authDomain: 'instagramclone-bbbee.firebaseapp.com',
    storageBucket: 'instagramclone-bbbee.appspot.com',
  );
}
